version: '3.8'

services:
  mysql_datos:
    image: mysql:8.0
    container_name: mysql_datos
    environment:
      MYSQL_ROOT_PASSWORD: utec
      MYSQL_DATABASE: empleados
    ports:
      - "3306:3306"
    networks:
      - red_bd

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - red_bd

  ingesta:
    build: .
    container_name: ingesta_s3
    depends_on:
      - mysql_datos
    environment:
      MYSQL_HOST: mysql_datos
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: utec
      MYSQL_DATABASE: empleados
      MYSQL_TABLE: empleados
      S3_BUCKET: s6-ingesta02
      AWS_ACCESS_KEY_ID: ASIAZAU3EM3EQLTNX43V
      AWS_SECRET_ACCESS_KEY: rzbNBogIy0lZcQKOiVBoqnewq+LX6soT1PX/kpZ5
      AWS_DEFAULT_REGION: us-east-1
    networks:
      - red_bd

networks:
  red_bd:
